# Generated by Django 5.2.3 on 2025-06-14 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
