# Generated by Django 5.2.3 on 2025-06-14 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='rest_user',
        ),
    ]
